"""AI/ML/Data Science smart group definitions for the 4u vertical."""

from typing import List, Tuple

SMART_GROUP_RULES: List[Tuple[str, List[str]]] = [
    (
        "Agentic AI & Automations",
        [
            "agentic ai",
            "agentic workflow",
            "ai agent",
            "ai agents",
            "multi-agent",
            "orchestration",
            "auto gpt",
            "autogpt",
            "babyagi",
            "crew ai",
            "function calling",
            "tool use",
            "action transformer",
            "state graph",
            "planning loop",
            "agent platform",
            "workflow studio",
        ],
    ),
    (
        "LLM & Foundation Model Releases",
        [
            "gpt-4",
            "gpt-5",
            "chatgpt",
            "openai",
            "anthropic",
            "claude",
            "gemini",
            "gemma",
            "google deepmind",
            "llama",
            "mistral",
            "cohere",
            "command r",
            "foundation model",
            "large language model",
            "model weights",
            "model release",
            "finetune available",
        ],
    ),
    (
        "AI Research & Papers",
        [
            "arxiv",
            "preprint",
            "neurips",
            "icml",
            "iclr",
            "siggraph",
            "benchmark",
            "state-of-the-art",
            "sota",
            "paper introduces",
            "transformer architecture",
            "evaluation suite",
            "leaderboard",
        ],
    ),
    (
        "MLOps & Deployment",
        [
            "mlops",
            "model serving",
            "feature store",
            "online inference",
            "deployment pipeline",
            "model registry",
            "monitoring drift",
            "continuous training",
            "productionizing",
            "vector database",
            "retrieval augmented generation",
            "rag pipeline",
        ],
    ),
    (
        "Data Engineering & Pipelines",
        [
            "data lakehouse",
            "data pipeline",
            "elt",
            "data mesh",
            "spark",
            "data quality",
            "data lineage",
            "feature engineering",
            "synthetic data",
            "dataset release",
            "open dataset",
            "metadata store",
        ],
    ),
    (
        "NLP & Language Understanding",
        [
            "nlp",
            "tokenizer",
            "embedding",
            "machine translation",
            "multilingual",
            "speech to text",
            "text generation",
            "semantic search",
            "information extraction",
            "named entity",
        ],
    ),
    (
        "Computer Vision & Multimodal",
        [
            "computer vision",
            "vision transformer",
            "multimodal",
            "image model",
            "video generation",
            "diffusion",
            "stable diffusion",
            "object detection",
            "scene reconstruction",
            "depth estimation",
        ],
    ),
    (
        "AI Hardware & Chips",
        [
            "gpu cluster",
            "nvidia",
            "h100",
            "blackwell",
            "gh200",
            "mi300",
            "ai accelerator",
            "inference chip",
            "tensor core",
            "ai supercomputer",
        ],
    ),
    (
        "AI Safety & Ethics",
        [
            "alignment",
            "ai safety",
            "responsible ai",
            "ethical ai",
            "bias mitigation",
            "red teaming",
            "hallucination",
            "jailbreak",
            "guardrails",
            "safety eval",
        ],
    ),
    (
        "AI Regulation & Policy",
        [
            "ai act",
            "policy framework",
            "regulator",
            "compliance",
            "governance",
            "executive order",
            "ai oversight",
            "auditability",
            "safe harbor",
        ],
    ),
    (
        "Data Science Practice",
        [
            "data scientist",
            "notebooks",
            "pandas",
            "numpy",
            "scikit",
            "statistics",
            "experimentation",
            "feature importance",
            "model interpretability",
            "evaluation methodology",
        ],
    ),
    (
        "AI Business & Funding",
        [
            "funding round",
            "series a",
            "acquisition",
            "valuation",
            "go-to-market",
            "enterprise ai",
            "ai startup",
            "partnership",
            "strategic alliance",
            "customer adoption",
        ],
    ),
]
