"""Smart groups for the Finnish general news vertical.

Rules are intentionally concise and Finnish‑language oriented. Matching is
case‑insensitive substring search over title + summary + source.
"""

from __future__ import annotations

from typing import List, Tuple

SMART_GROUP_RULES: List[Tuple[str, List[str]]] = [
    (
        "Terveys & Sote",
        [
            "terveys",
            "sote",
            "thl",
            "rokote",
            "rokotus",
            "influenssa",
            "flunssa",
            "korona",
            "covid",
            "sairaala",
            "hoitaja",
            "lääke",
            "lääkitys",
        ],
    ),
    (
        "Talous & Työ",
        [
            "talous",
            "kansantalous",
            "bkt",
            "bruttokansantuote",
            "inflaatio",
            "indeksi",
            "korko",
            "euribor",
            "budjetti",
            "vero",
            "verotus",
            "työllisyys",
            "työttömyys",
            "palkka",
            "ansiot",
            "yritys",
            "konkurssi",
            "investointi",
            "markkina",
            "rahoitus",
        ],
    ),
    (
        "Politiikka",
        [
            "hallitus",
            "eduskunta",
            "lainsäädäntö",
            "ministeri",
            "puolue",
            "vaalit",
            "presidentinvaalit",
            "oppositio",
        ],
    ),
    (
        "Kunnat & Alueet",
        [
            "kunta",
            "kaupunki",
            "kuntavaalit",
            "maakunta",
            "hyvinvointialue",
            "aluevaltuusto",
            "hus",
        ],
    ),
    (
        "Liikenne & Liikkuminen",
        [
            "liikenne",
            "liikennehäiriö",
            "ruuhka",
            "juna",
            "bussi",
            "raide",
            "linja-auto",
            "tie",
            "rata",
            "hsl",
            "vr ",
        ],
    ),
    (
        "Autot & Mobiliteetti",
        [
            "auto",
            "sähköauto",
            "lataus",
            "renkaat",
            "moottori",
            "liikenneturva",
        ],
    ),
    (
        "Teknologia & Tiede",
        [
            "teknologia",
            "tekoäly",
            "ai ",
            "tietotekniikka",
            "it ",
            "pilvi",
            "sovellus",
            "puhelin",
            "mobiili",
            "tiede",
            "tutkimus",
            "innovaati",
        ],
    ),
    (
        "Kulttuuri & Viihde",
        [
            "kulttuuri",
            "elokuva",
            "tv ",
            "sarja",
            "musiikki",
            "kirja",
            "näyttely",
            "museo",
            "teatteri",
            "festivaali",
            "julkkis",
            "kuninkaalliset",
        ],
    ),
    (
        "Urheilu",
        [
            "urheilu",
            "ottelu",
            "liiga",
            "sm-liiga",
            "veikkausliiga",
            "maajoukkue",
            "olympia",
            "mestaruus",
            "piste",
            "mitali",
            "jääkiekko",
            "futis",
            "jalkapallo",
            "koripallo",
            "pesäpallo",
            "hiihto",
            "ralli",
        ],
    ),
    (
        "Sää & Ilmasto",
        [
            "sää",
            "myrsky",
            "lumipyry",
            "pakkas",
            "helle",
            "ennuste",
            "ilmatieteen laitos",
            "ilmasto",
            "päästö",
            "hiilineutraali",
            "ympäristö",
            "luonto",
        ],
    ),
    (
        "Rikokset & Oikeus",
        [
            "poliisi",
            "rikos",
            "oikeudenkäynti",
            "tuomio",
            "syyte",
            "vankeus",
            "verkkorikos",
            "petos",
            "pahoinpitely",
            "käräjäoikeus",
            "hovioikeus",
            "kko",
        ],
    ),
    (
        "EU & Ulkomaat",
        [
            "eu ",
            "euroopan unioni",
            "bryssel",
            "komissio",
            "parlamentti",
            "nato",
            "ulkopolitiikka",
            "ukraina",
            "venäjä",
            "ruotsi",
            "norja",
            "yhdysvallat",
            "usa",
            "kiina",
            "viro",
        ],
    ),
    (
        "Asuminen & Rakentaminen",
        [
            "asuminen",
            "asunto",
            "asuntolaina",
            "vuokra",
            "rakentaminen",
            "korjausrakentaminen",
            "kaavoitus",
        ],
    ),
    (
        "Koulutus & Opetus",
        [
            "koulu",
            "opetus",
            "lukio",
            "yliopisto",
            "ammattikorkea",
            "oppilas",
            "opiskelija",
            "tentti",
            "opettaja",
        ],
    ),
    (
        "Energia",
        [
            "energia",
            "sähkö",
            "sähkön hinta",
            "fortum",
            "fingrid",
            "ydinvoima",
            "tuulivoima",
            "aurinkovoima",
            "polttoaine",
            "bensiini",
            "diesel",
        ],
    ),
    (
        "Ruoka & Kuluttaja",
        [
            "ruoka",
            "ravinto",
            "kuluttaja",
            "hintaseuranta",
            "alennus",
            "tarjous",
            "s-ryhmä",
            "k-ryhmä",
            "lidl",
        ],
    ),
]
