"""
Economics smart group definitions for the 'economics' vertical.

Rules here override the defaults in code/base/news_fetcher/smart_groups.py
when running the pipeline with --vertical economics (or VERTICAL=economics).

Classification is simple keyword matching against title + summary. Keep
keywords short, lowercase, and representative. Groups are non-exclusive.
"""

from typing import List, Tuple


SMART_GROUP_RULES: List[Tuple[str, List[str]]] = [
    (
        "Macro & Growth",
        [
            "gdp",
            "growth forecast",
            "recession",
            "macro ",
            "expansion",
            "contraction",
            "soft landing",
            "pmi",
            "industrial production",
            "retail sales",
            "leading indicator",
            "nowcast",
        ],
    ),
    (
        "Monetary Policy",
        [
            "rate hike",
            "rate cut",
            "interest rate",
            "tightening cycle",
            "easing cycle",
            "policy rate",
            "qe ",
            "qt ",
            "balance sheet",
            "forward guidance",
            "dot plot",
        ],
    ),
    (
        "Central Banks",
        [
            "federal reserve",
            "fed",
            "ecb",
            "bank of england",
            "boe",
            "boj",
            "bank of japan",
            "snb",
            "riksbank",
            "norges bank",
            "rba",
            "speeches",
            "minutes",
            "governor",
        ],
    ),
    (
        "Inflation & Prices",
        [
            "inflation",
            "disinflation",
            "deflation",
            "cpi",
            "pce",
            "core inflation",
            "headline inflation",
            "ppi",
            "wage-price",
        ],
    ),
    (
        "Labor & Wages",
        [
            "employment",
            "unemployment",
            "jobless claims",
            "nonfarm payrolls",
            "jolts",
            "wage growth",
            "labor market",
            "participation rate",
        ],
    ),
    (
        "Fiscal Policy & Debt",
        [
            "budget deficit",
            "debt ceiling",
            "fiscal package",
            "stimulus",
            "austerity",
            "treasury issuance",
            "primary balance",
        ],
    ),
    (
        "Trade & Supply Chains",
        [
            "exports",
            "export ",
            "imports",
            "import ",
            "trade balance",
            "wto",
            "tariff",
            "sanctions",
            "supply chain",
            "supply-chain",
            "logistics",
            "shipping",
            "port ",
            "freight",
            "reshoring",
            "nearshoring",
            "semiconductor",
            "chip ",
            "chips ",
            "foundry",
            "tsmc",
            "asml",
            "micron",
            "intel",
            "samsung",
            "manufacturing",
            "data center",
            "datacenter",
        ],
    ),
    (
        "Energy & Commodities",
        [
            "brent",
            "wti",
            "opec",
            "natgas",
            "lng",
            "coal",
            "metals",
            "copper",
            "nickel",
            "cobalt",
            "lithium",
            "gold",
            "uranium",
            "nuclear",
            "reactor",
            "battery",
            "refinery",
            "refineries",
            "mining",
            "commodity",
            "commodities",
            "iea",
            "eia",
        ],
    ),
    (
        "Markets & Rates",
        [
            "yields",
            "yield ",
            "treasuries",
            "bunds",
            "gilts",
            "curve steepening",
            "curve inversion",
            "equities",
            "stocks",
            "vix",
            "credit spreads",
            "basis points",
            " bps",
        ],
    ),
    (
        "Housing & Real Estate",
        [
            "housing starts",
            "building permits",
            "home sales",
            "mortgage rates",
            "real estate",
            "property ",
            "home price",
            "house price",
        ],
    ),
    (
        "Financial Stability",
        [
            "macroprudential",
            "macro-prudential",
            "stress test",
            "capital ratio",
            "basel",
            "liquidity coverage",
            "bank capital",
            "non-performing loans",
        ],
    ),
    (
        "Emerging Markets",
        [
            "emerging markets",
            "em ",
            "latam",
            "apac",
            "asean",
            "africa",
            "frontier markets",
            "venezuela",
            "kazakhstan",
            "uzbekistan",
            "central asia",
        ],
    ),
    (
        "China Economy",
        [
            "china economy",
            "pboC",
            "nbs china",
            "csdC",
            "property sector",
            "evergrande",
        ],
    ),
    (
        "US Economy",
        [
            "us economy",
            "beA ",
            "bls ",
            "ism manufacturing",
            "ism services",
        ],
    ),
    (
        "Euro Area",
        [
            "euro area",
            "eurozone",
            "euro area inflation",
            "hICP",
            "oecd europe",
        ],
    ),
    (
        "Nordics & Finland",
        [
            "finland economy",
            "bank of finland",
            "statistics finland",
            "riksbank",
            "norges bank",
        ],
    ),
    (
        "Climate & ESG Economics",
        [
            "carbon price",
            "emissions trading",
            "transition risk",
            "sustainability-linked",
            "green bond",
        ],
    ),
]
