"""
Threat actor names for detection and trend analysis.

This file contains a comprehensive list of threat actor names for automatic
detection in news content. To add or modify threat actors, edit the list below.
"""

from typing import List

# Comprehensive list of threat actor names
# Source: MITRE ATT&CK, CrowdStrike, Microsoft, and other threat intelligence sources
THREAT_ACTOR_NAMES: List[str] = [
    # APT Groups
    "APT-C-23",
    "APT-C-36",
    "APT1",
    "APT12",
    "APT16",
    "APT17",
    "APT18",
    "APT19",
    "APT28",
    "APT29",
    "APT3",
    "APT30",
    "APT32",
    "APT33",
    "APT37",
    "APT38",
    "APT39",
    "APT41",
    "APT42",
    "APT5",
    # Named Groups
    "Agrius",
    "Ajax Security Team",
    "Akira",
    "Andariel",
    "Aoqin Dragon",
    "AppleJeus",
    "Aquatic Panda",
    "Axiom",
    "BITTER",
    "BRONZE BUTLER",
    "BackdoorDiplomacy",
    "BlackByte",
    "BlackOasis",
    "BlackTech",
    "Blue Mockingbird",
    "CURIUM",
    "Carbanak",
    "Chimera",
    "Cinnamon Tempest",
    "Cleaver",
    "Cobalt Group",
    "Confucius",
    "Contagious Interview",
    "CopyKittens",
    "Daggerfly",
    "Dark Caracal",
    "DarkHydrus",
    "DarkVishnya",
    "Darkhotel",
    "Deep Panda",
    "DragonOK",
    "Dragonfly",
    "EXOTIC LILY",
    "Earth Lusca",
    "Elderwood",
    "Ember Bear",
    "Equation",
    "Evilnum",
    # FIN Groups
    "FIN10",
    "FIN13",
    "FIN4",
    "FIN5",
    "FIN6",
    "FIN7",
    "FIN8",
    "Ferocious Kitten",
    "Fox Kitten",
    "GALLIUM",
    "GCMAN",
    "GOLD SOUTHFIELD",
    "Gallmaker",
    "Gamaredon Group",
    "Gorgon Group",
    "Group5",
    "HAFNIUM",
    "HEXANE",
    "Higaisa",
    "INC Ransom",
    "Inception",
    "IndigoZebra",
    "Indrik Spider",
    "Ke3chang",
    "Kimsuky",
    "LAPSUS$",
    "Lazarus Group",
    "LazyScripter",
    "Leafminer",
    "Leviathan",
    "Lotus Blossom",
    "LuminousMoth",
    "Machete",
    "Magic Hound",
    "Malteiro",
    "Medusa Group",
    "Metador",
    "Moafee",
    "Mofang",
    "Molerats",
    "Moonstone Sleet",
    "Moses Staff",
    "MoustachedBouncer",
    "MuddyWater",
    "Mustang Panda",
    "Mustard Tempest",
    "NEODYMIUM",
    "Naikon",
    "Nomadic Octopus",
    "OilRig",
    "Orangeworm",
    "PLATINUM",
    "POLONIUM",
    "PROMETHIUM",
    "Patchwork",
    "PittyTiger",
    "Play",
    "Poseidon Group",
    "Putter Panda",
    "RTM",
    "Rancor",
    "RedCurl",
    "RedEcho",
    "Rocke",
    "Saint Bear",
    "Salt Typhoon",
    "Sandworm Team",
    "Scarlet Mimic",
    "Scattered Spider",
    "Sea Turtle",
    "SideCopy",
    "Sidewinder",
    "Silence",
    "Silent Librarian",
    "SilverTerrier",
    "Sowbug",
    "Star Blizzard",
    "Stealth Falcon",
    "Storm-0501",
    "Storm-1811",
    "Strider",
    "Suckfly",
    # TA Groups
    "TA2541",
    "TA459",
    "TA505",
    "TA551",
    "TA577",
    "TA578",
    "TEMP.Veles",
    "TeamTNT",
    "The White Company",
    "Threat Group-1314",
    "Threat Group-3390",
    "Thrip",
    "ToddyCat",
    "Tonto Team",
    "Transparent Tribe",
    "Tropic Trooper",
    "Turla",
    "UNC3886",
    "Velvet Ant",
    "Volatile Cedar",
    "Volt Typhoon",
    "WIRTE",
    "Water Galura",
    "Whitefly",
    "Windigo",
    "Windshift",
    "Winnti Group",
    "Winter Vivern",
    "Wizard Spider",
    "ZIRCONIUM",
    "admin@338",
    "menuPass",
    # Microsoft Taxonomy (Weather-based naming)
    "Amethyst Rain",
    "Antique Typhoon",
    "Aqua Blizzard",
    "Berry Sandstorm",
    "Blue Tsunami",
    "Brass Typhoon",
    "Brocade Typhoon",
    "Burgundy Sandstorm",
    "Cadet Blizzard",
    "Canary Typhoon",
    "Canvas Cyclone",
    "Caramel Tsunami",
    "Carmine Tsunami",
    "Charcoal Typhoon",
    "Checkered Typhoon",
    "Circle Typhoon",
    "Citrine Sleet",
    "Copper Typhoon",
    "Cotton Sandstorm",
    "CovertNetwork-1658",
    "Crescent Typhoon",
    "Crimson Sandstorm",
    "Cuboid Sandstorm",
    "Daffodil Gust",
    "Denim Tsunami",
    "Diamond Sleet",
    "Emerald Sleet",
    "Fallow Squall",
    "Flax Typhoon",
    "Forest Blizzard",
    "Ghost Blizzard",
    "Gingham Typhoon",
    "Granite Typhoon",
    "Gray Sandstorm",
    "Hazel Sandstorm",
    "Heart Typhoon",
    "Hexagon Typhoon",
    "Houndstooth Typhoon",
    "Jade Sleet",
    "Jasper Sleet",
    "Lace Tempest",
    "Lemon Sandstorm",
    "Leopard Typhoon",
    "Lilac Typhoon",
    "Linen Typhoon",
    "Luna Tempest",
    "Magenta Dust",
    "Manatee Tempest",
    "Mango Sandstorm",
    "Marbled Dust",
    "Marigold Sandstorm",
    "Midnight Blizzard",
    "Mint Sandstorm",
    "Mulberry Typhoon",
    "Neva Flood",
    "Night Tsunami",
    "Nylon Typhoon",
    "Octo Tempest",
    "Oka Flood",
    "Onyx Sleet",
    "Opal Sleet",
    "Patched Lightning",
    "Peach Sandstorm",
    "Pearl Sleet",
    "Pepper Typhoon",
    "Periwinkle Tempest",
    "Phlox Tempest",
    "Pink Sandstorm",
    "Pinstripe Lightning",
    "Pistachio Tempest",
    "Plaid Rain",
    "Pumpkin Sandstorm",
    "Purple Typhoon",
    "Raspberry Typhoon",
    "Red Sandstorm",
    "Ruby Sleet",
    "Ruza Flood",
    "Salmon Typhoon",
    "Sangria Tempest",
    "Sapphire Sleet",
    "Satin Typhoon",
    "Seashell Blizzard",
    "Secret Blizzard",
    "Sefid Flood",
    "Shadow Typhoon",
    "Silk Typhoon",
    "Smoke Sandstorm",
    "Spandex Tempest",
    # Storm Groups
    "Storm-0216",
    "Storm-0230",
    "Storm-0247",
    "Storm-0249",
    "Storm-0252",
    "Storm-0288",
    "Storm-0302",
    "Storm-0408",
    "Storm-0485",
    "Storm-0538",
    "Storm-0539",
    "Storm-0569",
    "Storm-0671",
    "Storm-0940",
    "Storm-0978",
    "Storm-1101",
    "Storm-1113",
    "Storm-1152",
    "Storm-1175",
    "Storm-1194",
    "Storm-1249",
    "Storm-1516",
    "Storm-1567",
    "Storm-1607",
    "Storm-1674",
    "Storm-1849",
    "Storm-1865",
    "Storm-1982",
    "Storm-2035",
    "Storm-2077",
    "Storm-2246",
    "Storm-2372",
    "Storm-2460",
    "Storm-2477",
    "Storm-2603",
    "Storm-2657",
    "Strawberry Tempest",
    "Sunglow Blizzard",
    "Swirl Typhoon",
    "Taffeta Typhoon",
    "Taizi Flood",
    "Tumbleweed Typhoon",
    "Twill Typhoon",
    "Vanilla Tempest",
    "Velvet Tempest",
    "Violet Typhoon",
    "Void Blizzard",
    "Volga Flood",
    "Wheat Tempest",
    "Wisteria Tsunami",
    "Yulong Flood",
    "Zigzag Hail",
    # CrowdStrike Taxonomy (Animal-based naming)
    "HAZARD SPIDER",
    "FROZEN SPIDER",
    "HERMIT SPIDER",
    "BITWISE SPIDER",
    "IMPOSTER SPIDER",
    "MUTANT SPIDER",
    "SCION SPIDER",
    "SLY SPIDER",
    "APOTHECARY SPIDER",
    "DEMON SPIDER",
    "VETO SPIDER",
    "VICE SPIDER",
    "SOLAR SPIDER",
    "TRAVELING SPIDER",
    "PLUMP SPIDER",
    "NITRO SPIDER",
    "CURLY SPIDER",
    "CHATTY SPIDER",
    "RENAISSANCE SPIDER",
    "PUNK SPIDER",
    "RECESS SPIDER",
    "BRAIN SPIDER",
    "SCATTERED SPIDER",
    "AVIATOR SPIDER",
    "PROPHET SPIDER",
    "GRACEFUL SPIDER",
    "SCULLY SPIDER",
    "BRASH SPIDER",
    "LIGHTNING SPIDER",
    "HOOK SPIDER",
    "HOLIDAY SPIDER",
    "SAMBA SPIDER",
    "LUNAR SPIDER",
    "LUXURY SPIDER",
    "NIMBLE SPIDER",
    "COOKIE SPIDER",
    "ROBOT SPIDER",
    "ODYSSEY SPIDER",
    "ROYAL SPIDER",
    "BLIND SPIDER",
    "WIZARD SPIDER",
    "BOUNTY JACKAL",
    "CRUEL JACKAL",
    "HORDE PANDA",
    "SUNRISE PANDA",
    "PHANTOM PANDA",
    "CASCADE PANDA",
    "LOTUS PANDA",
    "GENESIS PANDA",
    "WARP PANDA",
    "VERTIGO PANDA",
    "MUSTANG PANDA",
    "OPERATOR PANDA",
    "ENVOY PANDA",
    "GOSSAMER BEAR",
    "FANCY BEAR",
    "PRIMITIVE BEAR",
    "COZY BEAR",
    "VOODOO BEAR",
    "VENOMOUS BEAR",
    "FABLE TIGER",
    "OUTRIDER TIGER",
    "HAZY TIGER",
    "RAZOR TIGER",
    "FRANTIC TIGER",
    "FAMOUS CHOLLIMA",
    "LABYRINTH CHOLLIMA",
    "STARDUST CHOLLIMA",
    "HAYWIRE KITTEN",
    "SPECTRAL KITTEN",
    "GALACTIC OCELOT",
]


def get_threat_actor_names() -> List[str]:
    """
    Get list of threat actor names for detection.

    Returns:
        List of threat actor names
    """
    return THREAT_ACTOR_NAMES
